export const properties = [
    {
      id: 1,
      image: "link-to-image-1",
      title: "Semi furnished 2 BHK in kuvempu layout",
      price: 22500,
      deposit: 2,
      area: 800,
      location: "Visthar",
      ratings: 4.5,
      category: "Family",
    },
    {
      id: 2,
      image: "link-to-image-2",
      title: "Luxury 3 BHK in Whitefield",
      price: 45000,
      deposit: 3,
      area: 1200,
      location: "Whitefield",
      ratings: 4.8,
      category: "Luxury",
    },
    {
      id: 3,
      image: "link-to-image-3",
      title: "Affordable 1 BHK in BTM Layout",
      price: 15000,
      deposit: 1,
      area: 500,
      location: "BTM Layout",
      ratings: 4.0,
      category: "Budget",
    },
    {
      id: 4,
      image: "link-to-image-4",
      title: "Spacious 2 BHK in Electronic City",
      price: 25000,
      deposit: 2,
      area: 850,
      location: "Electronic City",
      ratings: 4.3,
      category: "Family",
    },
    {
      id: 5,
      image: "link-to-image-5",
      title: "Studio Apartment in Koramangala",
      price: 18000,
      deposit: 1,
      area: 400,
      location: "Koramangala",
      ratings: 4.2,
      category: "Single",
    },
    {
      id: 6,
      image: "link-to-image-6",
      title: "3 BHK Penthouse in Indiranagar",
      price: 55000,
      deposit: 4,
      area: 1400,
      location: "Indiranagar",
      ratings: 4.9,
      category: "Luxury",
    },
    {
      id: 7,
      image: "link-to-image-7",
      title: "Furnished 2 BHK in Marathahalli",
      price: 28000,
      deposit: 2,
      area: 900,
      location: "Marathahalli",
      ratings: 4.4,
      category: "Family",
    },
    {
      id: 8,
      image: "link-to-image-8",
      title: "Affordable 1 BHK in Yelahanka",
      price: 12000,
      deposit: 1,
      area: 450,
      location: "Yelahanka",
      ratings: 3.8,
      category: "Budget",
    },
    {
      id: 9,
      image: "link-to-image-9",
      title: "4 BHK Villa in Sarjapur Road",
      price: 60000,
      deposit: 5,
      area: 2000,
      location: "Sarjapur Road",
      ratings: 4.7,
      category: "Luxury",
    },
    {
      id: 10,
      image: "link-to-image-10",
      title: "Compact Studio in HSR Layout",
      price: 16000,
      deposit: 1,
      area: 350,
      location: "HSR Layout",
      ratings: 4.1,
      category: "Single",
    },
    {
      id: 11,
      image: "link-to-image-11",
      title: "Furnished 3 BHK in Jayanagar",
      price: 42000,
      deposit: 3,
      area: 1300,
      location: "Jayanagar",
      ratings: 4.6,
      category: "Family",
    },
    {
      id: 12,
      image: "link-to-image-12",
      title: "2 BHK with Balcony in Hebbal",
      price: 24000,
      deposit: 2,
      area: 900,
      location: "Hebbal",
      ratings: 4.3,
      category: "Family",
    },
    {
      id: 13,
      image: "link-to-image-13",
      title: "Luxury 2 BHK in Malleswaram",
      price: 35000,
      deposit: 3,
      area: 950,
      location: "Malleswaram",
      ratings: 4.7,
      category: "Luxury",
    },
    {
      id: 14,
      image: "link-to-image-14",
      title: "Affordable Studio in Banashankari",
      price: 13000,
      deposit: 1,
      area: 400,
      location: "Banashankari",
      ratings: 3.9,
      category: "Budget",
    },
    {
      id: 15,
      image: "link-to-image-15",
      title: "4 BHK Duplex in Richmond Town",
      price: 70000,
      deposit: 5,
      area: 2200,
      location: "Richmond Town",
      ratings: 4.8,
      category: "Luxury",
    },
  ];
  